Feature/monitoring
jarviscanada/jarvis_data_eng_james pull request #5
Opened 2019-11-28 21:17 UTC by jamesli9572

ticket [link](https://www.notion.so/Monitoring-Agenth-eccc57000f3749ad920fc247b8eb5885)
adding script to gather host info and usage

2019-11-29 13:55 UTC, ghost requested changes

2019-11-29 13:55 UTC, jarvisgroup commented on linux_sql/scripts/host_info.sh
> +#psql -h $psql_host -p $psql_port -U $psql_user -d $db_name -c "$insert_statement"
why comment out? please fix

2019-11-29 16:15 UTC, jamesli9572 commented on linux_sql/scripts/host_info.sh
> +#psql -h $psql_host -p $psql_port -U $psql_user -d $db_name -c "$insert_statement"
fixed

2019-12-01 21:57 UTC, ghost requested changes

2019-12-01 21:57 UTC, jarvisgroup commented on linux_sql/scripts/host_info.sh
> +psql -h $psql_host -p $psql_port -U $psql_user -d $db_name -c "$insert_statement"
exit 0

2019-12-02 03:02 UTC, jamesli9572 commented on linux_sql/scripts/host_info.sh
> +psql -h $psql_host -p $psql_port -U $psql_user -d $db_name -c "$insert_statement"
fixed

2019-12-02 16:32 UTC, merged